### PR TITLE
add basic bower.json file

### PR DESCRIPTION
**Pull request by whummer**
Basic config file for integration with bower. As suggested in https://github.com/aehlke/tag-it/issues/239

### CODE REVIEW

**Comment by ddegasperi** [comment]
Hi,
it would be nice, if this pull request could make it into the repo. I'm missing the bower support for this plugin.

Best regards,
Daniel

**Comment by PommeVerte** [comment]
looks good to me

**Comment by alangvara** [comment]
would be great!

**Comment by aehlke** [comment]
I still need to rebuild the minimized JS to accommodate this

**Pull request closed without merging**
